version: '3.9'
services:
  hades-server:
    build: .
    container_name: hades-server
    env_file:
      - .env.docker
    environment:
      DB_POSTGRES_HOST: db
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASS: ${DB_POSTGRES_PASS}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
      DB_POSTGRES_SSL: ${DB_POSTGRES_SSL}
      DB_POSTGRES_SYNC: ${DB_POSTGRES_SYNC}
      DB_POSTGRES_AUTO_LOAD: ${DB_POSTGRES_AUTO_LOAD}
      DB_POSTGRES_RUN_MIGRATIONS: ${DB_POSTGRES_RUN_MIGRATIONS}
      DB_POSTGRES_LOGGING: ${DB_POSTGRES_LOGGING}
      DB_POSTGRES_MIGRATIONS_TABLE_NAME: ${DB_POSTGRES_MIGRATIONS_TABLE_NAME}
      NATS_HOST: nats-server
      NATS_PROTOCOL: nats
      NATS_PORT_INT: ${NATS_PORT_INT:-4222}
      NATS_PORT_EXT: ${NATS_PORT_EXT:-4223}
      NATS_URL: "nats://${NATS_HOST}:${NATS_PORT_INT}"
      PORT: ${PORT:-3002}
    ports:
      - "${PORT:-3002}:3002"
    depends_on:
      - db
      - nats-server
    networks:
      - hades-net

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "${DB_POSTGRES_PORT:-5433}:5432"
    networks:
      - hades-net

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "${NATS_PORT_EXT:-4223}:4222"
    networks:
      - hades-net

networks:
  hades-net:
    driver: bridge