version: '3.8'

services:
  # Servicio de PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de NATS
  nats-server:
    image: nats:2.9.15
    container_name: nats-broker
    ports:
      - "${NATS_PORT_EXT}:${NATS_PORT_INT}"
    environment:
      - NATS_HOST=${NATS_HOST}
      - NATS_PROTOCOL=${NATS_PROTOCOL}

  # Servicio de tu microservicio NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hades-server
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
      - nats-server
    environment:
      # Variables de entorno para PostgreSQL
      DB_POSTGRES_HOST: db
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_TYPE: ${DB_POSTGRES_TYPE}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASS: ${DB_POSTGRES_PASS}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
      DB_POSTGRES_SSL: ${DB_POSTGRES_SSL}
      DB_POSTGRES_SYNC: ${DB_POSTGRES_SYNC}
      DB_POSTGRES_AUTO_LOAD: ${DB_POSTGRES_AUTO_LOAD}
      DB_POSTGRES_RUN_MIGRATIONS: ${DB_POSTGRES_RUN_MIGRATIONS}
      DB_POSTGRES_LOGGING: ${DB_POSTGRES_LOGGING}
      DB_POSTGRES_MIGRATIONS_TABLE_NAME: ${DB_POSTGRES_MIGRATIONS_TABLE_NAME}

      # Variables de entorno para NATS
      NATS_HOST: nats-server
      NATS_PROTOCOL: ${NATS_PROTOCOL}
      NATS_PORT: ${NATS_PORT_INT}
      NATS_URL: nats://${NATS_HOST}:${NATS_PORT_INT}

      # Variables de entorno para el servidor
      PORT: ${PORT:-3000}
    volumes:
      - ./src:/app/src
    command: sh -c "pnpm run typeorm:migration:run && pnpm run start:prod"

volumes:
  postgres_data:
