export const CMDS_HADES = {
  ROLE: {
    CREATE: 'HADES.CREATE.ROLE',
    DESTROY: 'HADES.DESTROY.ROLE',
    ARCHIVE: 'HADES.ARCHIVE.ROLE',
    UPDATE: 'HADES.UPDATE.ROLE',
    LIST: 'HADES.LIST.ROLE',
    GET: 'HADES.GET.ROLE',
  },
  USER: {
    CREATE: 'HADES.CREATE.USER',
    DESTROY: 'HADES.DESTROY.USER',
    ARCHIVE: 'HADES.ARCHIVE.USER',
    UPDATE: 'HADES.UPDATE.USER',
    LIST: 'HADES.LIST.USER',
    GET: 'HADES.GET.USER',
  },
  SESSION: {
    CREATE: 'HADES.CREATE.SESSION',
    ARCHIVE: 'HADES.ARCHIVE.SESSION',
  },
};
