import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableAssignments1738035760853 implements MigrationInterface {
  name = 'CreateTableAssignments1738035760853';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "assignments" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "archived_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "description" character varying(500), "role_id" integer, "user_id" integer, CONSTRAINT "UQ_9ca6a74af5f9823bd7fc6938a3a" UNIQUE ("uuid"), CONSTRAINT "REL_253fa3c633a343fd927f1191f7" UNIQUE ("role_id"), CONSTRAINT "REL_3e96b2dc80534b727b58b87b85" UNIQUE ("user_id"), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignment_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignment_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "fk_assignment_user_id"`);
    await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "fk_assignment_role_id"`);
    await queryRunner.query(`DROP TABLE "assignments"`);
  }
}
