export enum OperatorsEnum {
  EQ = 'eq',
  NE = 'ne',
  GT = 'gt',
  GTE = 'gte',
  LT = 'lt',
  LTE = 'lte',
  IN = 'in',
  NIN = 'nin',
  LIKE = 'like',
  N_LIKE = 'n_like',
  ILIKE = 'ilike',
  N_ILIKE = 'n_ilike',
  S_WITH = 's_with',
  E_WITH = 'e_with',
  BETWEEN = 'between',
  IS_NULL = 'is_null',
  IS_NOT_NULL = 'is_not_null',
  IS_EMPTY = 'is_empty',
  IS_NOT_EMPTY = 'is_not_empty',
  IS_TRUE = 'is_true',
  IS_FALSE = 'is_false',
  WI_DEL = 'wi_del',
}
